namespace: tp7-kustomize

  # On garde `images:` pour piloter le tag depuis l'overlay (démonstration rollout)
  # Ici on ne change pas le repository, seulement la version (newTag)
images:
- name: ghcr.io/wals110spring-petclinic
  newName: ghcr.io/wals110/spring-petclinic
  newTag: 4.0.1
- name: spring-petclinic
  newName: ghcr.io/wals110spring-petclinic
  newTag: 4c1b743dd5612c61be0181b01f351bf0f98f0a89

# Référencer la baseline (réutiliser tous les manifests de base/)
resources:
- ../base

# Appliquer les patches (modifications)
  # Type 1 : JSON Patch (replicas.yaml) - syntaxe très spécifique, ex: /spec/replicas
patches:
- path: replicas.yaml
  target:
    kind: Deployment
    name: clinic-deploy
- path: patch-routing.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
